//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BensHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BHubDbEntities : DbContext
    {
        public BHubDbEntities()
            : base("name=BHubDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VisitorMessage> VisitorMessages { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<SiteStatistic> SiteStatistics { get; set; }
    }
}
