//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BensHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VisitorMessage
    {
        public int Id { get; set; }

        public System.DateTime DateTime { get; set; }

        [Required]
        [MinLength(1), MaxLength(24)]
        public string Name { get; set; }

        [Required]
        [MinLength(1), MaxLength(68)]
        public string Message { get; set; }

    }
}
